### ISSUE TITLE
本讨论区对中文友好，请大胆用中文发言。

### ISSUE THREAD

**Issue by open-company** [open-company/quickstart#1]
当然，如果您英文还马马虎虎，就尽可能用英文发言。以利于国际友人的参与。

**Comment by lymanlai** [comment]
建议都用英文吧。。毕竟是要直接全球化的啊。因为是open company嘛。。

**Comment by open-company** [comment]
嘿嘿，英文对大部分国人来说还是有一定心理障碍的，包括我在内，说多了也露怯。
但是没办法啊，干了这行，工作性质决定了。没条件，创造条件也要上啊。

**Comment by lymanlai** [comment]
然后我该怎么开始项目？我想我可以先试试。

**Comment by lymanlai** [comment]
之前我用angularjs和restify及rethinkdb和FlatUI做过自己的idea。
现在我想可以在这里试试react及semantic-ui来从新搞一次，应该会快很多的吧

之前在restify里面用了async

**Comment by open-company** [comment]
先别着急，容我把文档和第一批项目先发布了。
然后，讨论出一个大家认可和接受的薪酬计算公式。
Open Company 成功与否的关键就在于薪酬计算的透明、公平、合理。
公式一旦确定，开发人员就可以真正当家作主了，因为排除了人为的干予。

现在文档还没完成，可能你的理解有一定偏差。
所谓的**项目**实际上是 Open Company Open Source Project 它是**属于**Open Company的项目。
也就是说是公司的项目，是体现公司的产品设计、经营意图和市场目标的项目。
即使今后大部分项目都是由开发人员提出的，这其实也是互联网公司的通行模式。大部分公司的项目肯定是由开发人员提供的。
这也是 Open Company 为什么是Company的本质所在，虽然它的运营方式是Open的，项目是Open Source的。

**Comment by ruanyl** [comment]
在cnodejs看了你的帖子，令人眼前一亮，从没看过startup用这种方式招募成员。如果这种模式成功，我相信对developer和supporter都将有巨大的吸引力。

除了薪资算法/方案，还很期待看到更多有关你们团队对项目管理方面的信息。比如项目协作/人员沟通等。持续关注中！

**Comment by open-company** [comment]
谢谢关注。
项目协作和人员沟通也全部基于Github，采用完全开放的方式。
因为所有项目都是开源的，因此，不光团队成员可参与，所有的Github上的开发者都可以参与。
如果某个项目对某个开发者有用，即使他不是团队成员，也有可能贡献代码或是帮助修复错误。
